"""link_url unique

Revision ID: 0e315e4db4a2
Revises: ac8ac3cb8541
Create Date: 2026-01-30 13:53:12.387119

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0e315e4db4a2'
down_revision: Union[str, Sequence[str], None] = 'ac8ac3cb8541'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'links', ['link_url'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'links', type_='unique')
    # ### end Alembic commands ###
