"""New deleted user

Revision ID: 1d524880af7a
Revises: e7feb3addadf
Create Date: 2026-01-23 12:16:06.322365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d524880af7a'
down_revision: Union[str, Sequence[str], None] = 'e7feb3addadf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('projects', 'curator',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('projects_users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer_minus',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               server_default='-1',
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer_minus',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('projects_users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    op.alter_column('projects', 'curator',
               existing_type=sa.INTEGER(),
               server_default=sa.text('19'),
               existing_nullable=False)
    # ### end Alembic commands ###
