"""series table director add

Revision ID: 2bf35e3bc494
Revises: ff29f35903e9
Create Date: 2026-02-24 01:48:14.796204

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2bf35e3bc494'
down_revision: Union[str, Sequence[str], None] = 'ff29f35903e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('raw_sound_engineer', sa.Integer(), server_default='-1', nullable=False))
    op.add_column('series', sa.Column('director', sa.Integer(), server_default='-1', nullable=False))
    op.drop_constraint(op.f('series_sound_engineer_minus_fkey'), 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'users', ['raw_sound_engineer'], ['user_id'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'series', 'users', ['director'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_column('series', 'sound_engineer_minus')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('sound_engineer_minus', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key(op.f('series_sound_engineer_minus_fkey'), 'series', 'users', ['sound_engineer_minus'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_column('series', 'director')
    op.drop_column('series', 'raw_sound_engineer')
    # ### end Alembic commands ###
