"""add is_active columns

Revision ID: 382bdf1a5f2e
Revises: 5da112e4c32f
Create Date: 2025-11-23 17:19:34.147359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '382bdf1a5f2e'
down_revision: Union[str, Sequence[str], None] = '5da112e4c32f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('levels', sa.Column('is_active', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('roles', 'is_active')
    op.drop_column('levels', 'is_active')
    # ### end Alembic commands ###
