"""cascade contacts deleting

Revision ID: 4d9eb52c2be0
Revises: 982fbd0f298e
Create Date: 2026-03-25 15:31:55.667880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4d9eb52c2be0'
down_revision: Union[str, Sequence[str], None] = '982fbd0f298e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('contacts_user_id_fkey'), 'contacts', type_='foreignkey')
    op.create_foreign_key(None, 'contacts', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'contacts', type_='foreignkey')
    op.create_foreign_key(op.f('contacts_user_id_fkey'), 'contacts', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
