"""projects deleting

Revision ID: 4fedda182699
Revises: 50ae7061177f
Create Date: 2026-02-20 18:07:36.509175

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4fedda182699'
down_revision: Union[str, Sequence[str], None] = '50ae7061177f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('project_links_project_id_fkey'), 'project_links', type_='foreignkey')
    op.create_foreign_key(None, 'project_links', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('project_role_history_project_id_fkey'), 'project_role_history', type_='foreignkey')
    op.create_foreign_key(None, 'project_role_history', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_users_project_id_fkey'), 'projects_users', type_='foreignkey')
    op.create_foreign_key(None, 'projects_users', 'projects', ['project_id'], ['project_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects_users', type_='foreignkey')
    op.create_foreign_key(op.f('projects_users_project_id_fkey'), 'projects_users', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_role_history', type_='foreignkey')
    op.create_foreign_key(op.f('project_role_history_project_id_fkey'), 'project_role_history', 'projects', ['project_id'], ['project_id'])
    op.drop_constraint(None, 'project_links', type_='foreignkey')
    op.create_foreign_key(op.f('project_links_project_id_fkey'), 'project_links', 'projects', ['project_id'], ['project_id'])
    # ### end Alembic commands ###
