"""nullable fields

Revision ID: 50cad6d09677
Revises: 2bf35e3bc494
Create Date: 2026-02-24 01:50:18.597691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '50cad6d09677'
down_revision: Union[str, Sequence[str], None] = '2bf35e3bc494'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'raw_sound_engineer',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'director',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series', 'director',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'raw_sound_engineer',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    # ### end Alembic commands ###
