"""delete profile tables

Revision ID: 56590feb6ad7
Revises: 35970bec632a
Create Date: 2026-01-19 22:11:38.309208

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56590feb6ad7"
down_revision: Union[str, Sequence[str], None] = "35970bec632a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "contacts",
        sa.Column("contact_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("link", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("contact_id"),
    )
    op.create_table(
        "users_series",
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("series_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["series_id"],
            ["series.id"],
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("user_id", "series_id"),
    )
    op.drop_constraint(op.f("roles_profile_id_fkey"), "roles", type_="foreignkey")
    op.drop_table("profile_series")
    op.drop_table("profiles")
    op.add_column("roles", sa.Column("user_id", sa.Integer(), nullable=False))
    op.create_foreign_key(None, "roles", "users", ["user_id"], ["user_id"])
    op.drop_column("roles", "profile_id")
    op.add_column("users", sa.Column("avatar_url", sa.String(), nullable=True))
    op.add_column("users", sa.Column("birth_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("join_date", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("description", sa.String(), nullable=True))
    op.add_column("users", sa.Column("rest_start", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("rest_end", sa.DateTime(), nullable=True))
    op.add_column("users", sa.Column("rest_reason", sa.String(), nullable=True))
    op.add_column("users", sa.Column("demo_url", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "demo_url")
    op.drop_column("users", "rest_reason")
    op.drop_column("users", "rest_end")
    op.drop_column("users", "rest_start")
    op.drop_column("users", "description")
    op.drop_column("users", "join_date")
    op.drop_column("users", "birth_date")
    op.drop_column("users", "avatar_url")
    op.add_column(
        "roles",
        sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    op.drop_constraint(None, "roles", type_="foreignkey")
    op.create_foreign_key(
        op.f("roles_profile_id_fkey"),
        "roles",
        "profiles",
        ["profile_id"],
        ["profile_id"],
    )
    op.drop_column("roles", "user_id")
    op.create_table(
        "profiles",
        sa.Column(
            "profile_id",
            sa.INTEGER(),
            server_default=sa.text("nextval('profiles_profile_id_seq'::regclass)"),
            autoincrement=True,
            nullable=False,
        ),
        sa.Column("user_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("birth_date", sa.DATE(), autoincrement=False, nullable=True),
        sa.Column(
            "registered_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "updated_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "is_active",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("avatar", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "rest_start", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "rest_end", postgresql.TIMESTAMP(), autoincrement=False, nullable=True
        ),
        sa.Column("demo_url", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.user_id"], name="profiles_user_id_fkey"
        ),
        sa.PrimaryKeyConstraint("profile_id", name="profiles_pkey"),
        sa.UniqueConstraint(
            "user_id",
            name="profiles_user_id_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "profile_series",
        sa.Column("profile_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.Column("series_id", sa.INTEGER(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["profile_id"],
            ["profiles.profile_id"],
            name=op.f("profile_series_profile_id_fkey"),
        ),
        sa.ForeignKeyConstraint(
            ["series_id"], ["series.id"], name=op.f("profile_series_series_id_fkey")
        ),
        sa.PrimaryKeyConstraint("series_id", name=op.f("profile_series_pkey")),
    )
    op.drop_table("users_series")
    op.drop_table("contacts")
    # ### end Alembic commands ###
