"""change users/profiles, add levels

Revision ID: 5da112e4c32f
Revises: d15720e4b89b
Create Date: 2025-11-23 17:09:30.257503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5da112e4c32f'
down_revision: Union[str, Sequence[str], None] = 'd15720e4b89b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('levels',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('role_name', sa.String(), nullable=False),
    sa.Column('access_level', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('level_id')
    )
    op.create_table('user_level',
    sa.Column('level_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['level_id'], ['levels.level_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('level_id', 'user_id')
    )
    op.drop_column('profiles', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_table('user_level')
    op.drop_table('levels')
    # ### end Alembic commands ###
