"""remove users_series table

Revision ID: 64237a4a64cb
Revises: 2595d2854fc9
Create Date: 2026-01-23 05:58:34.920640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64237a4a64cb'
down_revision: Union[str, Sequence[str], None] = '2595d2854fc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users_series')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_series',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('users_series_series_id_fkey')),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], name=op.f('users_series_user_id_fkey')),
    sa.PrimaryKeyConstraint('user_id', 'series_id', name=op.f('users_series_pkey'))
    )
    # ### end Alembic commands ###
