"""curator_id

Revision ID: 6b65e3a76ac5
Revises: f7bcdb7f6a1e
Create Date: 2026-02-06 10:43:35.409903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6b65e3a76ac5'
down_revision: Union[str, Sequence[str], None] = 'f7bcdb7f6a1e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('curator_id', sa.Integer(), server_default='-1', nullable=False))
    op.drop_constraint(op.f('projects_curator_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['curator_id'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_column('projects', 'curator')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('curator', sa.INTEGER(), server_default=sa.text("'-1'::integer"), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_curator_fkey'), 'projects', 'users', ['curator'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_column('projects', 'curator_id')
    # ### end Alembic commands ###
