"""add rests

Revision ID: 710a308aa99f
Revises: 90ca432bdeeb
Create Date: 2025-12-28 19:47:05.029830

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '710a308aa99f'
down_revision: Union[str, Sequence[str], None] = '90ca432bdeeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profiles', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('profiles', sa.Column('rest_start', sa.DateTime(), nullable=True))
    op.add_column('profiles', sa.Column('rest_end', sa.DateTime(), nullable=True))
    op.add_column('roles', sa.Column('profile_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('roles_user_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'profiles', ['profile_id'], ['profile_id'])
    op.drop_column('roles', 'user_id')
    op.add_column('series', sa.Column('srt_url', sa.String(), nullable=False))
    op.add_column('series', sa.Column('ass_url', sa.String(), nullable=False))
    op.drop_column('series', 'srt')
    op.drop_column('series', 'ass')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('ass', sa.TEXT(), autoincrement=False, nullable=False))
    op.add_column('series', sa.Column('srt', sa.TEXT(), autoincrement=False, nullable=False))
    op.drop_column('series', 'ass_url')
    op.drop_column('series', 'srt_url')
    op.add_column('roles', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_user_id_fkey'), 'roles', 'users', ['user_id'], ['user_id'])
    op.drop_column('roles', 'profile_id')
    op.drop_column('profiles', 'rest_end')
    op.drop_column('profiles', 'rest_start')
    op.drop_column('profiles', 'description')
    # ### end Alembic commands ###
