"""public_contact in users table

Revision ID: 81ca6b47d5f2
Revises: f3659e431225
Create Date: 2026-03-30 12:05:19.857677

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '81ca6b47d5f2'
down_revision: Union[str, Sequence[str], None] = 'f3659e431225'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ass_fixes',
    sa.Column('fix_id', sa.Integer(), nullable=False),
    sa.Column('fix_note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('fix_id')
    )
    op.add_column('users', sa.Column('public_contact', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'public_contact')
    op.drop_table('ass_fixes')
    # ### end Alembic commands ###
