"""records, fixes, materials, links tables

Revision ID: 8abaeb5466d3
Revises: fdff073bf00c
Create Date: 2026-02-21 19:03:45.694177

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8abaeb5466d3'
down_revision: Union[str, Sequence[str], None] = 'fdff073bf00c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('material_title', sa.String(), nullable=False),
    sa.Column('material_prev_title', sa.String(), nullable=False),
    sa.Column('material_link', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('record_url', sa.String(), nullable=False),
    sa.Column('record_prev_title', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('series_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('link_title', sa.String(), nullable=False),
    sa.Column('link_url', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('phrase', sa.Integer(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.Column('ready', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('role_series')
    op.add_column('roles', sa.Column('role_name', sa.String(), nullable=False))
    op.add_column('roles', sa.Column('note', sa.String(), nullable=False))
    op.add_column('roles', sa.Column('checked', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('timed', sa.Boolean(), nullable=False))
    op.add_column('roles', sa.Column('state', sa.String(), nullable=False))
    op.drop_column('roles', 'result_url')
    op.drop_column('roles', 'name')
    op.drop_column('roles', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('roles', sa.Column('result_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('roles', 'state')
    op.drop_column('roles', 'timed')
    op.drop_column('roles', 'checked')
    op.drop_column('roles', 'note')
    op.drop_column('roles', 'role_name')
    op.create_table('role_series',
    sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('series_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], name=op.f('role_series_role_id_fkey')),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], name=op.f('role_series_series_id_fkey')),
    sa.PrimaryKeyConstraint('role_id', 'series_id', name=op.f('role_series_pkey'))
    )
    op.drop_table('fixes')
    op.drop_table('series_links')
    op.drop_table('records')
    op.drop_table('materials')
    # ### end Alembic commands ###
