"""change roles/series tables

Revision ID: 90ca432bdeeb
Revises: b2bd972967c8
Create Date: 2025-12-11 22:40:26.528668

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '90ca432bdeeb'
down_revision: Union[str, Sequence[str], None] = 'b2bd972967c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('user_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('roles_profile_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['user_id'])
    op.drop_column('roles', 'profile_id')
    op.add_column('series', sa.Column('srt', sa.Text(), nullable=False))
    op.add_column('series', sa.Column('ass', sa.Text(), nullable=False))
    op.add_column('series', sa.Column('sound_engineer_minus', sa.Integer(), nullable=False))
    op.add_column('series', sa.Column('timer', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('series_sound_engineer_2_fkey'), 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'users', ['timer'], ['user_id'])
    op.create_foreign_key(None, 'series', 'users', ['sound_engineer_minus'], ['user_id'])
    op.drop_column('series', 'sound_engineer_2')
    op.drop_column('series', 'srt_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('srt_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('series', sa.Column('sound_engineer_2', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key(op.f('series_sound_engineer_2_fkey'), 'series', 'users', ['sound_engineer_2'], ['user_id'])
    op.drop_column('series', 'timer')
    op.drop_column('series', 'sound_engineer_minus')
    op.drop_column('series', 'ass')
    op.drop_column('series', 'srt')
    op.add_column('roles', sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_profile_id_fkey'), 'roles', 'profiles', ['profile_id'], ['profile_id'])
    op.drop_column('roles', 'user_id')
    # ### end Alembic commands ###
