"""Preparing to delete a user

Revision ID: 91d3a3e94e1a
Revises: 64237a4a64cb
Create Date: 2026-01-23 07:28:50.544114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91d3a3e94e1a'
down_revision: Union[str, Sequence[str], None] = '64237a4a64cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('projects_curator_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'users', ['curator'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_constraint(op.f('projects_users_user_id_fkey'), 'projects_users', type_='foreignkey')
    op.create_foreign_key(None, 'projects_users', 'users', ['user_id'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_constraint(op.f('roles_user_id_fkey'), 'roles', type_='foreignkey')
    op.create_foreign_key(None, 'roles', 'users', ['user_id'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_constraint(op.f('series_translator_fkey'), 'series', type_='foreignkey')
    op.drop_constraint(op.f('series_timer_fkey'), 'series', type_='foreignkey')
    op.drop_constraint(op.f('series_sound_engineer_fkey'), 'series', type_='foreignkey')
    op.drop_constraint(op.f('series_curator_fkey'), 'series', type_='foreignkey')
    op.drop_constraint(op.f('series_sound_engineer_minus_fkey'), 'series', type_='foreignkey')
    op.create_foreign_key(None, 'series', 'users', ['sound_engineer'], ['user_id'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'series', 'users', ['timer'], ['user_id'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'series', 'users', ['translator'], ['user_id'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'series', 'users', ['sound_engineer_minus'], ['user_id'], ondelete='SET DEFAULT')
    op.create_foreign_key(None, 'series', 'users', ['curator'], ['user_id'], ondelete='SET DEFAULT')
    op.drop_constraint(op.f('user_level_user_id_fkey'), 'user_level', type_='foreignkey')
    op.drop_constraint(op.f('user_level_level_id_fkey'), 'user_level', type_='foreignkey')
    op.create_foreign_key(None, 'user_level', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'user_level', 'levels', ['level_id'], ['level_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_level', type_='foreignkey')
    op.drop_constraint(None, 'user_level', type_='foreignkey')
    op.create_foreign_key(op.f('user_level_level_id_fkey'), 'user_level', 'levels', ['level_id'], ['level_id'])
    op.create_foreign_key(op.f('user_level_user_id_fkey'), 'user_level', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.drop_constraint(None, 'series', type_='foreignkey')
    op.create_foreign_key(op.f('series_sound_engineer_minus_fkey'), 'series', 'users', ['sound_engineer_minus'], ['user_id'])
    op.create_foreign_key(op.f('series_curator_fkey'), 'series', 'users', ['curator'], ['user_id'])
    op.create_foreign_key(op.f('series_sound_engineer_fkey'), 'series', 'users', ['sound_engineer'], ['user_id'])
    op.create_foreign_key(op.f('series_timer_fkey'), 'series', 'users', ['timer'], ['user_id'])
    op.create_foreign_key(op.f('series_translator_fkey'), 'series', 'users', ['translator'], ['user_id'])
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.create_foreign_key(op.f('roles_user_id_fkey'), 'roles', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'projects_users', type_='foreignkey')
    op.create_foreign_key(op.f('projects_users_user_id_fkey'), 'projects_users', 'users', ['user_id'], ['user_id'])
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_curator_fkey'), 'projects', 'users', ['curator'], ['user_id'])
    # ### end Alembic commands ###
