"""Foreign Keys add

Revision ID: 958c47c98cc3
Revises: 8abaeb5466d3
Create Date: 2026-02-23 22:07:04.448582

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '958c47c98cc3'
down_revision: Union[str, Sequence[str], None] = '8abaeb5466d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('materials', sa.Column('series_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'materials', 'series', ['series_id'], ['id'])
    op.add_column('records', sa.Column('role_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'records', 'roles', ['role_id'], ['role_id'], ondelete='CASCADE')
    op.add_column('roles', sa.Column('series_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'roles', 'series', ['series_id'], ['id'], ondelete='CASCADE')
    op.add_column('series_links', sa.Column('series_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'series_links', 'series', ['series_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'series_links', type_='foreignkey')
    op.drop_column('series_links', 'series_id')
    op.drop_constraint(None, 'roles', type_='foreignkey')
    op.drop_column('roles', 'series_id')
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.drop_column('records', 'role_id')
    op.drop_constraint(None, 'materials', type_='foreignkey')
    op.drop_column('materials', 'series_id')
    # ### end Alembic commands ###
