"""series table update

Revision ID: 982fbd0f298e
Revises: 22bbfc59a2e5
Create Date: 2026-03-23 19:49:18.737742

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '982fbd0f298e'
down_revision: Union[str, Sequence[str], None] = '22bbfc59a2e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('note', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('series', 'note')
    # ### end Alembic commands ###
