"""Delete ProjectProfile, add ProjectUser

Revision ID: 9ef37f967f32
Revises: bf0b3c186329
Create Date: 2025-12-01 20:16:59.010732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9ef37f967f32'
down_revision: Union[str, Sequence[str], None] = 'bf0b3c186329'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects_users',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'project_id')
    )
    op.drop_table('project_profiles')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_profiles',
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('profile_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], name=op.f('project_profiles_profile_id_fkey')),
    sa.ForeignKeyConstraint(['project_id'], ['projects.project_id'], name=op.f('project_profiles_project_id_fkey')),
    sa.PrimaryKeyConstraint('project_id', 'profile_id', name=op.f('project_profiles_pkey'))
    )
    op.drop_table('projects_users')
    # ### end Alembic commands ###
