"""cascade role_history deleting

Revision ID: b17e145276dc
Revises: 4d9eb52c2be0
Create Date: 2026-03-25 15:47:42.057839

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b17e145276dc'
down_revision: Union[str, Sequence[str], None] = '4d9eb52c2be0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('role_history_user_id_fkey'), 'role_history', type_='foreignkey')
    op.create_foreign_key(None, 'role_history', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'role_history', type_='foreignkey')
    op.create_foreign_key(op.f('role_history_user_id_fkey'), 'role_history', 'users', ['user_id'], ['user_id'])
    # ### end Alembic commands ###
