"""fix

Revision ID: bf0b3c186329
Revises: 382bdf1a5f2e
Create Date: 2025-11-23 19:02:57.158307

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "bf0b3c186329"
down_revision: Union[str, Sequence[str], None] = "382bdf1a5f2e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "access_level")
    # ### end Alembic commands ###
    # Для users.is_active
    op.alter_column(
        "users", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )

    # Для profiles.is_active
    op.alter_column(
        "profiles", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )

    # Для projects.is_active
    op.alter_column(
        "projects", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )

    # Для series.is_active
    op.alter_column(
        "series", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )
    op.alter_column(
        "levels", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )
    op.alter_column(
        "roles", "is_active", existing_type=sa.Boolean(), server_default=sa.true()
    )


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column("access_level", sa.INTEGER(), autoincrement=False, nullable=False),
    )
    # ### end Alembic commands ###
