"""create roles table

Revision ID: d15720e4b89b
Revises: 25f15dd77580
Create Date: 2025-11-23 15:56:26.333395

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd15720e4b89b'
down_revision: Union[str, Sequence[str], None] = '25f15dd77580'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('profile_id', sa.Integer(), nullable=False),
    sa.Column('srt_url', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('result_url', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['profile_id'], ['profiles.profile_id'], ),
    sa.PrimaryKeyConstraint('role_id')
    )
    op.create_table('role_series',
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('series_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.role_id'], ),
    sa.ForeignKeyConstraint(['series_id'], ['series.id'], ),
    sa.PrimaryKeyConstraint('role_id', 'series_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_series')
    op.drop_table('roles')
    # ### end Alembic commands ###
