"""Project Plan table

Revision ID: d295ace07bbb
Revises: b3c4d5e6f7a8
Create Date: 2026-05-19 18:54:26.438910

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd295ace07bbb'
down_revision: Union[str, Sequence[str], None] = 'b3c4d5e6f7a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_plans',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('publication_date', sa.Date(), nullable=False),
    sa.Column('way', sa.String(), nullable=False),
    sa.Column('link', sa.String(), nullable=False),
    sa.Column('note', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_constraint(op.f('ass_fixes_series_id_fkey'), 'ass_fixes', type_='foreignkey')
    op.create_foreign_key(None, 'ass_fixes', 'series', ['series_id'], ['id'], ondelete='CASCADE')
    op.alter_column('records', 'record_note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('series', 'state',
               existing_type=postgresql.ENUM('подготовка материалов', 'озвучка', 'сведение', 'публикация', 'проверка', 'завершено', name='seriesstate'),
               type_=sa.Enum('подготовка материалов', 'озвучка', 'сведение', 'проверка', 'публикация', 'завершено', name='seriesstate', native_enum=False),
               existing_nullable=False,
               existing_server_default=sa.text("'подготовка материалов'::seriesstate"))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('series', 'state',
               existing_type=sa.Enum('подготовка материалов', 'озвучка', 'сведение', 'проверка', 'публикация', 'завершено', name='seriesstate', native_enum=False),
               type_=postgresql.ENUM('подготовка материалов', 'озвучка', 'сведение', 'публикация', 'проверка', 'завершено', name='seriesstate'),
               existing_nullable=False,
               existing_server_default=sa.text("'подготовка материалов'::seriesstate"))
    op.alter_column('records', 'record_note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'ass_fixes', type_='foreignkey')
    op.create_foreign_key(op.f('ass_fixes_series_id_fkey'), 'ass_fixes', 'series', ['series_id'], ['id'])
    op.drop_table('project_plans')
    # ### end Alembic commands ###
