"""try server_default

Revision ID: e7feb3addadf
Revises: 91d3a3e94e1a
Create Date: 2026-01-23 10:41:51.268711

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7feb3addadf'
down_revision: Union[str, Sequence[str], None] = '91d3a3e94e1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('levels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'curator',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects_users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer_minus',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               server_default='19',
               existing_nullable=False)
    op.alter_column('series', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('series', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('series', 'translator',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'timer',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer_minus',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'sound_engineer',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'curator',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('roles', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects_users', 'user_id',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('projects', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('projects', 'curator',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('levels', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    # ### end Alembic commands ###
