"""project_role_history reworking

Revision ID: f3659e431225
Revises: b17e145276dc
Create Date: 2026-03-25 17:53:23.736052

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3659e431225'
down_revision: Union[str, Sequence[str], None] = 'b17e145276dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_role_history', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'project_role_history', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
    op.drop_column('project_role_history', 'user_nickname')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('project_role_history', sa.Column('user_nickname', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'project_role_history', type_='foreignkey')
    op.drop_column('project_role_history', 'user_id')
    # ### end Alembic commands ###
