"""series and role tables fixes

Revision ID: ff29f35903e9
Revises: 958c47c98cc3
Create Date: 2026-02-24 01:39:52.324241

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff29f35903e9'
down_revision: Union[str, Sequence[str], None] = '958c47c98cc3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True,
               existing_server_default=sa.text("'-1'::integer"))
    op.alter_column('roles', 'note',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('series', sa.Column('state', sa.Enum('подготовка материалов', 'озвучка', 'сведение', 'публикация', 'завершено', name='seriesstate', native_enum=False), server_default='подготовка материалов', nullable=False))
    op.alter_column('series', 'start_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('series', 'first_deadline',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('series', 'second_deadline',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('series', 'exp_publish_date',
               existing_type=sa.DATE(),
               server_default=sa.text('CURRENT_DATE'),
               existing_nullable=False)
    op.alter_column('series', 'ass_url',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('series', 'srt_url')
    op.drop_column('series', 'result_url')
    op.drop_column('series', 'is_active')
    op.drop_column('series', 'raw_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('series', sa.Column('raw_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('series', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('series', sa.Column('result_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('series', sa.Column('srt_url', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.alter_column('series', 'ass_url',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('series', 'exp_publish_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'second_deadline',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'first_deadline',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('series', 'start_date',
               existing_type=sa.DATE(),
               server_default=None,
               existing_nullable=False)
    op.drop_column('series', 'state')
    op.alter_column('roles', 'note',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('roles', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False,
               existing_server_default=sa.text("'-1'::integer"))
    # ### end Alembic commands ###
