name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create database.py from secret
        shell: bash
        run: |
          cat << 'EOF' > app/database.py
          ${{ secrets.BS }}
          EOF

      - name: Create alembic.ini
        shell: bash
        run: |
          cat << 'EOF' > alembic.ini
          ${{ secrets.AI }}
          EOF

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO --delete"
          SOURCE: "./" # Исходники вашего бэкенда
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/www/back/"

      - name: Apply Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/back
            
            # Проверяем, существует ли папка venv
            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi
            
            # Активируем
            source venv/bin/activate
            
            # Устанавливаем зависимости (на случай, если они обновились)
            pip install -r requirements.txt
            
            # Запускаем миграции
            alembic upgrade head

      - name: Restart FastAPI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Перезагружаем сервис, чтобы применились изменения кода
            systemctl restart RM_server