name: Deploy Backend

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install -r requirements-test.txt

      - name: Create database.py for tests
        run: |
          cat << 'EOF' > app/database.py
          from sqlalchemy.ext.asyncio import create_async_engine, async_sessionmaker, AsyncSession
          from sqlalchemy.orm import DeclarativeBase

          DATABASE_URL = "sqlite+aiosqlite:///./test_redmic.db"

          engine = create_async_engine(DATABASE_URL, echo=False)
          async_session_maker = async_sessionmaker(engine, expire_on_commit=False)

          class Base(DeclarativeBase):
              pass

          async def get_db() -> AsyncSession:
              async with async_session_maker() as session:
                  yield session
          EOF

      - name: Run tests
        run: pytest

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Create database.py from secret
        shell: bash
        run: |
          cat << 'EOF' > app/database.py
          ${{ secrets.BS }}
          EOF

      - name: Create alembic.ini
        shell: bash
        run: |
          cat << 'EOF' > alembic.ini
          ${{ secrets.AI }}
          EOF

      - name: Deploy to Server
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.KEY }}
          ARGS: "-rltgoDzvO --delete --filter='merge .rsync-filter'"
          SOURCE: "./" # Исходники вашего бэкенда
          REMOTE_HOST: ${{ secrets.HOST }}
          REMOTE_USER: ${{ secrets.USERNAME }}
          TARGET: "/var/www/back/"

      - name: Apply Database Migrations
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            cd /var/www/back
            
            # Проверяем, существует ли папка venv
            if [ ! -d "venv" ]; then
              echo "Creating virtual environment..."
              python3 -m venv venv
            fi
            
            # Активируем
            source venv/bin/activate
            
            # Устанавливаем зависимости (на случай, если они обновились)
            pip install -r requirements.txt
            
            # Запускаем миграции
            alembic upgrade head

      - name: Restart FastAPI
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            # Перезагружаем сервис, чтобы применились изменения кода
            systemctl restart RM_server